// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2VcJ4QWAbthlX3x6MIseo-rQcZFwdB5A',
    appId: '1:63571855478:web:c0b64568e76c62f9ddb757',
    messagingSenderId: '63571855478',
    projectId: 'taraweehapp786',
    authDomain: 'taraweehapp786.firebaseapp.com',
    storageBucket: 'taraweehapp786.firebasestorage.app',
    measurementId: 'G-FTC6EM6JGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ACCqdtc1q_W-71w_A49Wdshz2TagR6M',
    appId: '1:63571855478:android:2b9c42810bab517addb757',
    messagingSenderId: '63571855478',
    projectId: 'taraweehapp786',
    storageBucket: 'taraweehapp786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATM37GOVVOKherY2VmV3ITm6ncX78tEgk',
    appId: '1:63571855478:ios:cf31af8560c6a9abddb757',
    messagingSenderId: '63571855478',
    projectId: 'taraweehapp786',
    storageBucket: 'taraweehapp786.firebasestorage.app',
    iosBundleId: 'com.example.lastpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2VcJ4QWAbthlX3x6MIseo-rQcZFwdB5A',
    appId: '1:63571855478:web:8af7783ef0d7cc12ddb757',
    messagingSenderId: '63571855478',
    projectId: 'taraweehapp786',
    authDomain: 'taraweehapp786.firebaseapp.com',
    storageBucket: 'taraweehapp786.firebasestorage.app',
    measurementId: 'G-MSRXK6S0WQ',
  );
}
